### ISSUE TITLE
just installed the mod and it says a bunch of files are missing

### ISSUE THREAD

**Issue by MoltenSilverIII** [p2sr/Portal2SpeedrunMod#11] opened 2022-10-17 13:42 UTC
first it said game sounds manifest was missing, so i took that from the normal portal 2 files and put it in, and now it says cant find background image 'materials/console/portal2_product_2_widescreen.vtf' which i cant even find in the portal 2 files

**Comment by ThisAMJ** [comment] 2022-10-23 10:58
Duplicate of #6

**Closed as completed** 2023-10-15 21:34 UTC
